language: python

python:
 - "3.6"

install: pip install -e .

script: pytest

deploy:
  provider: pypi
  user: creditas
  password:
    secure: gk38arUW0MdGrc0pn88nFiqkCzLROAXXqYPwgusq7i1cv1deYw67ohyYU7IgKTsHoicm2+y0HlwG0BcKRMrr4W3A+OWXLf5WznVzRw8yTWTa+cOdYroLDmSUWiUP6Gp6DhHDpu1wi/DEFsWPL/S36GL8CrslZQ1ZAqKeLPAgEYdAo1aQFw7F78YOni38u+Tz3hQJXzlvFdeWaP1aSDU28myHdvHzOeN5nsfJg9sgMQUkvGs7OPbLR7+Iixi1d9Ghbw1CSoqEjMOQUyeMqZrF55GvmfXz5696DmG3Mjsnd6ZNTKiqAvFP0SksqHnMya1brGmo7ZX+ZrHzRPrKDS4oujhZkMqsSEmk11UYc9uzIu2w5SP54sDv+rSqDIbjgO6x0Y1TBKuXmv1Wlc8LJSZ/M2BOL1ExsXQS0phXOfCFUX+i7lf0TOGC3EWGlNfzvdHO842uAJ2gNUwdqeegTT4NwBD0b2kqsamwG1SVbsBN092pf0oCbfKoCcTp8e/eKolqe90p/w5vPj77WOmsbXs/z/OMH3OnS22IlN2WKJ3Ii9xaaZm0onpNCTNoPyjABQXF6YLoHrPrO+TjugMcJOJNAPgyPWkwiYLiEieW33PUW0wAH6cz4d0ul43uJbpkEiLI+L2oHQysOPzjczSxjj6y23AzbEC1ve7teMo54IJ2fXw=
  on:
    branch: master
    tags: true
