language: python

python:
 - "3.6"

install: pip install -e .

script: pytest

deploy:
  provider: pypi
  user: creditas
  password:
    secure: "jO33zOYzyPBrqp95/KGJPd7ToB6OZ0it29IlMCTdKYJGF0VhcYxKcqiqD9nHk4oYCCmu7+nmTE7ghPdXY8FsJs/qV70BOpVPZS5iBSDV23AlA9msS0WQM/L8egi5fNFJrh/cM/ubQr+nHR45Lu2r+azbd9iiq2YE5Fez873VSSDH5rXk0dZbI9J+pnhohG3NdgHU16dzbhej1iFPyu9WpH7DJ6I9YEXpDjfbwcYq8/Nc42yW4ukpWc82ehVmUARa7amJp0DXwqaK6vpu902t8t3ah+gb5rHf6mNMnn8r4i6b+Ur/jNVi4UyRmoDyefoBMzHvZP7XjHtvmVXTsx9vmO3ixN0SMSQEKyLbdF8nwyIfqzRspHNqgyxkop03YD+v+lppdlOG77p19eb07Yg0d15e45d5OA1Qn473frn9/DCczVoQN9CvOHcMbb9BvhPM1VndPow3oJnFZxSpQUklX1OAW/Gio/7yrsjHDUH5gt5buEN+xe4OW1ot8c0Oye3JNX6/e2uGB3F9cGCgy7ab/1HIzeWa8hTV/E5sCLSy6P8ePU0C3f6JaON1Cja8uDjmVvHuhgod89Cfvlwb9CFRCO3Br4RrB0fGoasUgkx16CfIPq+tkZLvCnJxE/FhOpkOiWvaWBcZ7c9wtVeRwE1yX2K+TNCX/ETq9koPhE6PXKw="
  on:
    branch: master
